import { Router } from 'express';
import { z } from 'zod';
import { q, tx } from '../db.js';
import { asyncRoute, HttpError } from '../utils/http.js';
import { requireUser, roles } from '../middleware/auth.js';
import { audit } from '../services/audit.js';
const r=Router();
const equipmentSchema=z.object({fridges:z.number().int().min(0).max(30).default(1),freezers:z.number().int().min(0).max(20).default(1),coldRoomsPositive:z.number().int().min(0).max(10).default(0),coldRoomsNegative:z.number().int().min(0).max(10).default(0),displayFridges:z.number().int().min(0).max(20).default(0),fryers:z.number().int().min(0).max(20).default(0)});
const controlsSchema=z.object({temperaturePerDay:z.number().int().min(1).max(3).default(2),cleaning:z.boolean().default(true),dlc:z.boolean().default(true),handwash:z.boolean().default(true),oil:z.boolean().default(true),closingTime:z.string().regex(/^\d{2}:\d{2}$/).default('22:00')});
r.get('/',requireUser,roles('owner'),asyncRoute(async(req,res)=>{const {rows}=await q(`SELECT o.name,o.business_type,o.onboarding_step,o.onboarding_completed,s.equipment,s.controls,s.preferences FROM organizations o LEFT JOIN organization_settings s ON s.organization_id=o.id WHERE o.id=$1`,[req.user.organization_id]);res.json(rows[0]);}));
r.put('/step/:step',requireUser,roles('owner'),asyncRoute(async(req,res)=>{const step=Number(req.params.step);if(step<1||step>5)throw new HttpError(400,'Étape invalide.');if(step===1){const d=z.object({name:z.string().min(2),businessType:z.string().min(2),phone:z.string().max(30).optional(),address:z.string().max(200).optional(),postalCode:z.string().max(20).optional(),city:z.string().max(100).optional()}).parse(req.body);await q(`UPDATE organizations SET name=$1,business_type=$2,phone=$3,address=$4,postal_code=$5,city=$6,onboarding_step=GREATEST(onboarding_step,2) WHERE id=$7`,[d.name,d.businessType,d.phone||null,d.address||null,d.postalCode||null,d.city||null,req.user.organization_id]);}
  else if(step===2){const d=equipmentSchema.parse(req.body);await q(`UPDATE organization_settings SET equipment=$1,updated_at=now() WHERE organization_id=$2`,[d,req.user.organization_id]);await q(`UPDATE organizations SET onboarding_step=GREATEST(onboarding_step,3) WHERE id=$1`,[req.user.organization_id]);}
  else if(step===3){const d=controlsSchema.parse(req.body);await q(`UPDATE organization_settings SET controls=$1,updated_at=now() WHERE organization_id=$2`,[d,req.user.organization_id]);await q(`UPDATE organizations SET onboarding_step=GREATEST(onboarding_step,4) WHERE id=$1`,[req.user.organization_id]);}
  else if(step===4){await q(`UPDATE organizations SET onboarding_step=GREATEST(onboarding_step,5) WHERE id=$1`,[req.user.organization_id]);}
  else if(step===5){await tx(async c=>{const settings=(await c.query(`SELECT * FROM organization_settings WHERE organization_id=$1`,[req.user.organization_id])).rows[0];const eq=settings?.equipment||{},controls=settings?.controls||{};const existing=(await c.query(`SELECT count(*)::int n FROM records WHERE organization_id=$1 AND type IN ('equipment','task')`,[req.user.organization_id])).rows[0].n;if(!existing){const addEq=async(name,kind,min,max)=>c.query(`INSERT INTO records(organization_id,type,title,payload,created_by) VALUES($1,'equipment',$2,$3,$4)`,[req.user.organization_id,name,{kind,min,max},req.user.id]);for(let i=1;i<=Number(eq.fridges||0);i++)await addEq(`Réfrigérateur ${i}`,'fridge',0,4);for(let i=1;i<=Number(eq.freezers||0);i++)await addEq(`Congélateur ${i}`,'freezer',-25,-18);for(let i=1;i<=Number(eq.coldRoomsPositive||0);i++)await addEq(`Chambre froide + ${i}`,'cold_room_positive',0,4);for(let i=1;i<=Number(eq.coldRoomsNegative||0);i++)await addEq(`Chambre froide - ${i}`,'cold_room_negative',-25,-18);for(let i=1;i<=Number(eq.displayFridges||0);i++)await addEq(`Vitrine réfrigérée ${i}`,'display_fridge',0,4);for(let i=1;i<=Number(eq.fryers||0);i++)await addEq(`Friteuse ${i}`,'fryer',null,null);const tasks=[];if(controls.cleaning)tasks.push(['Nettoyage quotidien','cleaning']);if(controls.dlc)tasks.push(['Contrôle des DLC/DDM','dlc']);if(controls.handwash)tasks.push(['Vérification lave-mains','handwash']);if(controls.oil&&Number(eq.fryers||0)>0)tasks.push(['Contrôle des huiles','oil']);for(const [title,kind] of tasks)await c.query(`INSERT INTO records(organization_id,type,title,payload,created_by) VALUES($1,'task',$2,$3,$4)`,[req.user.organization_id,title,{kind,frequency:'daily',due:controls.closingTime||'22:00'},req.user.id]);}await c.query(`UPDATE organizations SET onboarding_completed=true,onboarding_step=5 WHERE id=$1`,[req.user.organization_id]);});}
  await audit(req,'onboarding.step','organization',req.user.organization_id,{step});res.json({ok:true,step,completed:step===5});
}));
export default r;
