import { Router } from 'express';
import { z } from 'zod';
import { q,tx } from '../db.js';
import { requireUser } from '../middleware/auth.js';
import { asyncRoute,HttpError } from '../utils/http.js';
import { audit } from '../services/audit.js';
import { parseGs1 } from '../utils/gs1.js';
import { lookupProduct, rememberProduct, normalizeBarcode } from '../services/product-lookup.js';

const r=Router();
const uuid=z.string().uuid();
const createSchema=z.object({kind:z.enum(['series','reception']),supplierId:z.string().uuid().nullish()});
const itemSchema=z.object({
  productName:z.string().trim().max(180).optional().nullable(),barcode:z.string().trim().max(100).optional().nullable(),rawCode:z.string().trim().max(300).optional().nullable(),
  lot:z.string().trim().max(100).optional().nullable(),expiryDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),dateType:z.enum(['dlc','ddm','expiry','unknown']).optional().default('unknown'),
  quantity:z.coerce.number().positive().max(100000).default(1),mediaId:z.string().uuid().optional().nullable(),payload:z.record(z.string(),z.any()).optional().default({})
});
const checkSchema=itemSchema.pick({productName:true,barcode:true,rawCode:true,lot:true,expiryDate:true});
const parseSchema=z.object({rawCode:z.string().trim().min(4).max(300)});
const rememberSchema=z.object({name:z.string().trim().min(1).max(220).optional().nullable()});
const norm=s=>String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ');
const sameText=(a,b)=>!!a&&!!b&&norm(a)===norm(b);
const todayIso=()=>new Date().toISOString().slice(0,10);
const daysUntil=iso=>Math.ceil((new Date(`${iso}T12:00:00Z`).getTime()-Date.now())/86400000);

async function getSession(org,id){
  const s=(await q(`SELECT ss.*,s.name supplier_name,po.order_number,i.invoice_number FROM scan_sessions ss LEFT JOIN suppliers s ON s.id=ss.supplier_id LEFT JOIN purchase_orders po ON po.id=ss.purchase_order_id LEFT JOIN supplier_invoice_imports i ON i.id=ss.invoice_import_id WHERE ss.id=$1 AND ss.organization_id=$2`,[id,org])).rows[0];
  if(!s)throw new HttpError(404,'Session de scan introuvable.','scan_session_not_found');return s;
}
function assertSessionWrite(req,session){if(req.user.role==='employee'&&session.created_by!==req.user.id)throw new HttpError(403,'Vous ne pouvez modifier que votre propre session de scan.','scan_session_forbidden');}
async function findArticle(org,{barcode,productName}){
  const code=String(barcode||'').replace(/\D/g,'');const name=String(productName||'').trim();
  if(!code&&!name)return null;
  return (await q(`SELECT id,title,payload FROM records WHERE organization_id=$1 AND type='stock_article' AND status<>'deleted' AND (($2::text<>'' AND regexp_replace(COALESCE(payload->>'barcode',''),'[^0-9]','','g')=$2) OR ($3::text<>'' AND lower(btrim(COALESCE(payload->>'product',title)))=lower(btrim($3)))) ORDER BY CASE WHEN $2::text<>'' AND regexp_replace(COALESCE(payload->>'barcode',''),'[^0-9]','','g')=$2 THEN 0 ELSE 1 END,updated_at DESC LIMIT 1`,[org,code,name])).rows[0]||null;
}
async function duplicateInfo(org,{barcode,productName,lot,expiryDate},sessionId=null){
  const code=String(barcode||'').replace(/\D/g,'');const name=String(productName||'').trim(),lotN=norm(lot),date=expiryDate||'';
  let record=null;
  if(code||name){const rows=(await q(`SELECT id,type,title,payload,created_at FROM records WHERE organization_id=$1 AND type IN ('traceability','reception') AND created_at>now()-interval '30 days' AND (($2::text<>'' AND regexp_replace(COALESCE(payload->>'barcode',''),'[^0-9]','','g')=$2) OR ($3::text<>'' AND lower(btrim(COALESCE(payload->>'product',title)))=lower(btrim($3)))) ORDER BY created_at DESC LIMIT 30`,[org,code,name])).rows;
    record=rows.find(x=>{const p=x.payload||{},sameLot=!lotN||norm(p.lot)===lotN,sameDate=!date||[p.expiry,p.dlc,p.expiryDate].filter(Boolean).includes(date);return sameLot&&sameDate})||null;}
  let sessionItem=null;
  if(code||name){const params=sessionId?[org,sessionId]:[org];const rows=(await q(`SELECT * FROM scan_session_items WHERE organization_id=$1 AND created_at>now()-interval '30 days' ${sessionId?'AND session_id<>$2':''} ORDER BY created_at DESC LIMIT 100`,params)).rows;sessionItem=rows.find(x=>{const identity=(code&&String(x.barcode||x.gtin||'').replace(/\D/g,'')===code)||(!code&&sameText(x.product_name,name));return identity&&(!lotN||norm(x.lot)===lotN)&&(!date||String(x.expiry_date||'').slice(0,10)===date)})||null;}
  if(!sessionItem&&sessionId&&(code||name)){const rows=(await q(`SELECT * FROM scan_session_items WHERE organization_id=$1 AND session_id=$2 ORDER BY created_at DESC`,[org,sessionId])).rows;sessionItem=rows.find(x=>{const identity=(code&&String(x.barcode||x.gtin||'').replace(/\D/g,'')===code)||(!code&&sameText(x.product_name,name));return identity&&(!lotN||norm(x.lot)===lotN)&&(!date||String(x.expiry_date||'').slice(0,10)===date)})||null;}
  return {duplicate:!!(record||sessionItem),record,sessionItem};
}
async function orderLineContext(session,article,{productName}){
  if(!session.purchase_order_id)return null;
  const rows=(await q(`SELECT * FROM purchase_order_lines WHERE order_id=$1`,[session.purchase_order_id])).rows;
  return rows.find(x=>(article?.id&&x.stock_article_id===article.id)||sameText(x.product_name,productName))||null;
}
async function invoiceLineContext(session,article,{productName}){
  if(!session.invoice_import_id)return null;
  const rows=(await q(`SELECT * FROM supplier_invoice_import_lines WHERE import_id=$1`,[session.invoice_import_id])).rows;
  return rows.find(x=>(article?.id&&x.stock_article_id===article.id)||sameText(x.product_name,productName))||null;
}
function anomalyLabel(code){return ({duplicate:'Doublon possible',expired:'DLC dépassée',expiry_soon:'DLC très proche',lot_missing:'Lot absent',unknown_product:'Produit non configuré dans le catalogue',not_ordered:'Produit non commandé',over_ordered:'Quantité reçue supérieure à la commande'})[code]||code;}

r.post('/parse-code',requireUser,asyncRoute(async(req,res)=>{const d=parseSchema.parse(req.body);res.json(parseGs1(d.rawCode));}));
r.get('/products',requireUser,asyncRoute(async(req,res)=>{const search=String(req.query.search||'').trim().slice(0,120),limit=Math.max(1,Math.min(250,Number(req.query.limit)||100));const params=[req.user.organization_id];let where='organization_id=$1';if(search){params.push(`%${search}%`);where+=` AND (product_name ILIKE $2 OR COALESCE(brand,'') ILIKE $2 OR barcode ILIKE $2)`;}params.push(limit);const rows=(await q(`SELECT id,barcode,product_name,brand,category,quantity_label,image_url,source,source_url,source_license,source_data,first_seen_at,last_seen_at,seen_count,updated_at FROM organization_product_memory WHERE ${where} ORDER BY last_seen_at DESC LIMIT $${params.length}`,params)).rows;res.json(rows.map(x=>({...x,sourceLabel:x.source_data?.sourceLabel||x.source||'HygieSafe'})));}));
r.get('/products/:code',requireUser,asyncRoute(async(req,res)=>{const parsed=parseGs1(String(req.params.code||'')),code=normalizeBarcode(parsed?.gtin||req.params.code);if(!code)throw new HttpError(400,'Code-barres EAN / GTIN invalide.','invalid_barcode');const forceRefresh=String(req.query.refresh||'')==='1'&&req.user.role!=='employee';const result=await lookupProduct({organizationId:req.user.organization_id,code,forceRefresh});res.json({...result,gs1VerificationUrl:'https://www.gs1.org/services/verified-by-gs1'});}));
r.post('/products/:code/remember',requireUser,asyncRoute(async(req,res)=>{const d=rememberSchema.parse(req.body||{}),parsed=parseGs1(String(req.params.code||'')),code=normalizeBarcode(parsed?.gtin||req.params.code);if(!code)throw new HttpError(400,'Code-barres EAN / GTIN invalide.','invalid_barcode');const lookup=await lookupProduct({organizationId:req.user.organization_id,code});let product=lookup.found?lookup.product:null;if(!product&&d.name)product={code,name:d.name,source:'manual',sourceLabel:'Saisie validée',sourceAttribution:'Produit renseigné et validé dans cet établissement',verifiedByGs1Url:'https://www.gs1.org/services/verified-by-gs1'};if(!product)throw new HttpError(404,'Produit introuvable. Renseignez son nom pour le mémoriser.','product_not_found');const row=await rememberProduct({organizationId:req.user.organization_id,userId:req.user.id,code,product,overrideName:d.name||null,allowRename:req.user.role!=='employee'});await audit(req,'scanner.product.remember','product_memory',row?.id||null,{barcode:code,source:product.source||'manual'});res.json({ok:true,product:{...product,name:d.name||product.name},memoryId:row?.id||null});}));
r.post('/check',requireUser,asyncRoute(async(req,res)=>{let d=checkSchema.parse(req.body),gs1=d.rawCode?parseGs1(d.rawCode):null;if(gs1?.isGs1)d={...d,barcode:d.barcode||gs1.gtin,lot:d.lot||gs1.lot,expiryDate:d.expiryDate||gs1.expiryDate};const dup=await duplicateInfo(req.user.organization_id,d);res.json({duplicate:dup.duplicate,record:dup.record?{id:dup.record.id,type:dup.record.type,title:dup.record.title,createdAt:dup.record.created_at}:null});}));

r.get('/sessions/active',requireUser,asyncRoute(async(req,res)=>{const s=(await q(`SELECT ss.*,sp.name supplier_name,po.order_number,i.invoice_number,(SELECT count(*)::int FROM scan_session_items x WHERE x.session_id=ss.id) item_count,(SELECT COALESCE(sum(cardinality(x.anomaly_codes)),0)::int FROM scan_session_items x WHERE x.session_id=ss.id) anomaly_count FROM scan_sessions ss LEFT JOIN suppliers sp ON sp.id=ss.supplier_id LEFT JOIN purchase_orders po ON po.id=ss.purchase_order_id LEFT JOIN supplier_invoice_imports i ON i.id=ss.invoice_import_id WHERE ss.organization_id=$1 AND ss.created_by=$2 AND ss.status='open' ORDER BY ss.started_at DESC LIMIT 1`,[req.user.organization_id,req.user.id])).rows[0]||null;res.json(s);}));
r.post('/sessions',requireUser,asyncRoute(async(req,res)=>{const d=createSchema.parse(req.body),org=req.user.organization_id;const open=(await q(`SELECT id,kind FROM scan_sessions WHERE organization_id=$1 AND created_by=$2 AND status='open' ORDER BY started_at DESC LIMIT 1`,[org,req.user.id])).rows[0];if(open)throw new HttpError(409,'Une session de scan est déjà en cours. Terminez-la avant d’en créer une nouvelle.','scan_session_already_open');if(d.kind==='reception'&&!d.supplierId)throw new HttpError(400,'Choisissez le fournisseur pour une réception intelligente.','supplier_required');let po=null,inv=null,supplier=null;if(d.supplierId){supplier=(await q(`SELECT id,name FROM suppliers WHERE id=$1 AND organization_id=$2 AND active=true`,[d.supplierId,org])).rows[0];if(!supplier)throw new HttpError(404,'Fournisseur introuvable.');po=(await q(`SELECT id,order_number FROM purchase_orders WHERE organization_id=$1 AND supplier_id=$2 AND status='submitted' ORDER BY submitted_at DESC LIMIT 1`,[org,d.supplierId])).rows[0]||null;inv=(await q(`SELECT id,invoice_number FROM supplier_invoice_imports WHERE organization_id=$1 AND supplier_id=$2 ORDER BY created_at DESC LIMIT 1`,[org,d.supplierId])).rows[0]||null;}
  const s=(await q(`INSERT INTO scan_sessions(organization_id,created_by,kind,supplier_id,purchase_order_id,invoice_import_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[org,req.user.id,d.kind,d.supplierId||null,po?.id||null,inv?.id||null])).rows[0];await audit(req,'scanner.session.start','scan_session',s.id,{kind:d.kind,supplierId:d.supplierId||null,purchaseOrderId:po?.id||null,invoiceImportId:inv?.id||null});res.status(201).json({...s,supplier_name:supplier?.name||null,order_number:po?.order_number||null,invoice_number:inv?.invoice_number||null,item_count:0,anomaly_count:0});}));
r.get('/sessions/:id',requireUser,asyncRoute(async(req,res)=>{const id=uuid.parse(req.params.id),s=await getSession(req.user.organization_id,id);assertSessionWrite(req,s);const items=(await q(`SELECT * FROM scan_session_items WHERE session_id=$1 AND organization_id=$2 ORDER BY created_at`,[id,req.user.organization_id])).rows;res.json({...s,items,item_count:items.length,anomaly_count:items.reduce((n,x)=>n+(x.anomaly_codes?.length||0),0)});}));

r.post('/sessions/:id/items',requireUser,asyncRoute(async(req,res)=>{const id=uuid.parse(req.params.id),org=req.user.organization_id,session=await getSession(org,id);assertSessionWrite(req,session);if(session.status!=='open')throw new HttpError(409,'Cette session de scan est déjà terminée.','scan_session_closed');let d=itemSchema.parse(req.body),gs1=d.rawCode?parseGs1(d.rawCode):null;if(gs1?.isGs1)d={...d,barcode:d.barcode||gs1.gtin,lot:d.lot||gs1.lot,expiryDate:d.expiryDate||gs1.expiryDate,dateType:d.dateType!=='unknown'?d.dateType:(gs1.dateType||'unknown'),quantity:d.quantity||gs1.quantity||1,payload:{...d.payload,gs1}};
  if(d.mediaId){const ok=(await q(`SELECT id FROM media WHERE id=$1 AND organization_id=$2`,[d.mediaId,org])).rows[0];if(!ok)throw new HttpError(400,'Photo de scan introuvable.','scan_media_missing');}
  const article=await findArticle(org,d);if(article&&!d.productName)d.productName=article.payload?.product||article.title;
  const lookupCode=normalizeBarcode(gs1?.gtin||d.barcode);let internetLookup=null;if(!article&&lookupCode){try{internetLookup=await lookupProduct({organizationId:org,code:lookupCode});if(internetLookup?.found&&!d.productName)d.productName=internetLookup.product?.name||null}catch{internetLookup=null;}}
  const dup=await duplicateInfo(org,d,id);const orderLine=await orderLineContext(session,article,d),invoiceLine=await invoiceLineContext(session,article,d);const anomalies=[];
  if(dup.duplicate)anomalies.push('duplicate');if(d.expiryDate){const n=daysUntil(d.expiryDate);if(n<0)anomalies.push('expired');else if(n<=3)anomalies.push('expiry_soon');}if(!d.lot)anomalies.push('lot_missing');if(!article&&!internetLookup?.found)anomalies.push('unknown_product');if(session.kind==='reception'&&session.purchase_order_id&&!orderLine)anomalies.push('not_ordered');
  let receivedBefore=0;if(orderLine){const rows=(await q(`SELECT quantity,stock_article_id,product_name FROM scan_session_items WHERE session_id=$1`,[id])).rows;receivedBefore=rows.filter(x=>(article?.id&&x.stock_article_id===article.id)||sameText(x.product_name,d.productName)).reduce((n,x)=>n+Number(x.quantity||0),0);if(receivedBefore+Number(d.quantity)>Number(orderLine.quantity||0)+.0001)anomalies.push('over_ordered');}
  const externalProduct=internetLookup?.found?internetLookup.product:null;const payload={...d.payload,matchedProduct:article?{id:article.id,title:article.payload?.product||article.title}:null,internetProduct:externalProduct?{code:externalProduct.code,name:externalProduct.name,brand:externalProduct.brand||null,category:externalProduct.category||null,source:externalProduct.source,sourceLabel:externalProduct.sourceLabel,sourceUrl:externalProduct.sourceUrl||null,sourceLicense:externalProduct.sourceLicense||null}:null,order:orderLine?{id:orderLine.id,orderedQuantity:Number(orderLine.quantity),unit:orderLine.order_unit}:null,invoice:invoiceLine?{id:invoiceLine.id,invoicedQuantity:Number(invoiceLine.invoice_quantity||0),unit:invoiceLine.order_unit}:null,anomalyLabels:anomalies.map(anomalyLabel)};
  const row=(await q(`INSERT INTO scan_session_items(session_id,organization_id,created_by,stock_article_id,media_id,product_name,barcode,gtin,raw_code,lot,expiry_date,date_type,quantity,anomaly_codes,duplicate_record_id,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *`,[id,org,req.user.id,article?.id||null,d.mediaId||null,d.productName||article?.title||externalProduct?.name||null,d.barcode||null,gs1?.gtin||d.barcode||null,d.rawCode||null,d.lot||null,d.expiryDate||null,d.dateType||'unknown',d.quantity,[...new Set(anomalies)],dup.record?.id||null,payload])).rows[0];
  if(lookupCode&&(d.productName||externalProduct?.name)){const remembered=externalProduct||{code:lookupCode,name:d.productName,source:'manual',sourceLabel:'Saisie validée',sourceAttribution:'Produit renseigné et validé dans cet établissement'};await rememberProduct({organizationId:org,userId:req.user.id,code:lookupCode,product:remembered,overrideName:d.productName||null}).catch(()=>{});}
  const productSource=externalProduct?.source||(article?'hygiesafe_catalog':'manual');await audit(req,'scanner.session.item','scan_session_item',row.id,{sessionId:id,anomalies:row.anomaly_codes,productSource});res.status(201).json({...row,anomaly_labels:row.anomaly_codes.map(anomalyLabel),internet_product:externalProduct});}));

r.delete('/sessions/:sessionId/items/:itemId',requireUser,asyncRoute(async(req,res)=>{const sid=uuid.parse(req.params.sessionId),iid=uuid.parse(req.params.itemId),s=await getSession(req.user.organization_id,sid);assertSessionWrite(req,s);if(s.status!=='open')throw new HttpError(409,'Cette session est terminée.');const {rowCount}=await q(`DELETE FROM scan_session_items WHERE id=$1 AND session_id=$2 AND organization_id=$3`,[iid,sid,req.user.organization_id]);if(!rowCount)throw new HttpError(404,'Scan introuvable.');res.json({ok:true});}));

r.post('/sessions/:id/cancel',requireUser,asyncRoute(async(req,res)=>{const id=uuid.parse(req.params.id),org=req.user.organization_id,s=await getSession(org,id);assertSessionWrite(req,s);if(s.status!=='open')throw new HttpError(409,'Cette session est déjà terminée.','scan_session_closed');await q(`UPDATE scan_sessions SET status='cancelled',completed_at=now(),summary=jsonb_build_object('cancelled',true) WHERE id=$1 AND organization_id=$2`,[id,org]);await audit(req,'scanner.session.cancel','scan_session',id,{kind:s.kind});res.json({ok:true});}));

r.post('/sessions/:id/complete',requireUser,asyncRoute(async(req,res)=>{const id=uuid.parse(req.params.id),org=req.user.organization_id,session=await getSession(org,id);assertSessionWrite(req,session);if(session.status!=='open')throw new HttpError(409,'Cette session est déjà terminée.','scan_session_closed');const items=(await q(`SELECT * FROM scan_session_items WHERE session_id=$1 AND organization_id=$2 ORDER BY created_at`,[id,org])).rows;if(!items.length)throw new HttpError(400,'Scannez au moins un produit avant de terminer.','empty_scan_session');let discrepancies=[];
  if(session.kind==='reception'&&session.purchase_order_id){const lines=(await q(`SELECT * FROM purchase_order_lines WHERE order_id=$1 ORDER BY product_name`,[session.purchase_order_id])).rows;for(const line of lines){const received=items.filter(x=>(line.stock_article_id&&x.stock_article_id===line.stock_article_id)||sameText(x.product_name,line.product_name)).reduce((n,x)=>n+Number(x.quantity||0),0),ordered=Number(line.quantity||0);if(received<ordered-.0001)discrepancies.push({code:'short_received',product:line.product_name,ordered,received,difference:received-ordered});else if(received>ordered+.0001)discrepancies.push({code:'over_received',product:line.product_name,ordered,received,difference:received-ordered});}}
  if(session.kind==='reception'&&session.invoice_import_id){const lines=(await q(`SELECT * FROM supplier_invoice_import_lines WHERE import_id=$1 ORDER BY sort_order`,[session.invoice_import_id])).rows;for(const line of lines){const received=items.filter(x=>(line.stock_article_id&&x.stock_article_id===line.stock_article_id)||sameText(x.product_name,line.product_name)).reduce((n,x)=>n+Number(x.quantity||0),0),invoiced=Number(line.invoice_quantity||0);if(invoiced>received+.0001)discrepancies.push({code:'billed_more_than_received',product:line.product_name,invoiced,received,difference:received-invoiced});else if(received>invoiced+.0001&&invoiced>0)discrepancies.push({code:'received_more_than_billed',product:line.product_name,invoiced,received,difference:received-invoiced});}}
  const anomalyItems=items.filter(x=>x.anomaly_codes?.length);const summary={itemCount:items.length,quantityTotal:items.reduce((n,x)=>n+Number(x.quantity||0),0),anomalyItemCount:anomalyItems.length,anomalyCount:anomalyItems.reduce((n,x)=>n+x.anomaly_codes.length,0),discrepancyCount:discrepancies.length,discrepancies,completedBy:req.user.id};
  await tx(async c=>{if(session.kind==='series'){for(const x of items){const p={source:'scanner_series',scanSessionId:id,scanItemId:x.id,product:x.product_name||'Produit scanné',lot:x.lot||null,expiry:x.expiry_date||null,dlc:x.expiry_date||null,dateType:x.date_type||'unknown',barcode:x.barcode||x.gtin||null,quantity:Number(x.quantity||1),scanMediaId:x.media_id||null,anomalies:x.anomaly_codes||[],scanVerified:true};await c.query(`INSERT INTO records(organization_id,type,title,status,payload,created_by,updated_by) VALUES($1,'traceability',$2,'active',$3,$4,$4)`,[org,x.product_name||'Produit scanné',p,req.user.id]);}}
    else{const payload={source:'scanner_reception_batch',scanSessionId:id,supplierId:session.supplier_id,purchaseOrderId:session.purchase_order_id,invoiceImportId:session.invoice_import_id,items:items.map(x=>({id:x.id,product:x.product_name,barcode:x.barcode||x.gtin,lot:x.lot,dlc:x.expiry_date,quantity:Number(x.quantity),anomalies:x.anomaly_codes,mediaId:x.media_id})),summary};await c.query(`INSERT INTO records(organization_id,type,title,status,payload,created_by,updated_by) VALUES($1,'reception',$2,'done',$3,$4,$4)`,[org,`Réception · ${session.supplier_name||'Fournisseur'}`,payload,req.user.id]);const serious=[...new Set([...items.flatMap(x=>x.anomaly_codes||[]).filter(x=>['expired','not_ordered','over_ordered'].includes(x)),...discrepancies.map(x=>x.code)])];if(serious.length)await c.query(`INSERT INTO records(organization_id,type,title,status,payload,created_by,updated_by) VALUES($1,'nonconformity',$2,'open',$3,$4,$4)`,[org,`Écart de réception · ${session.supplier_name||'Fournisseur'}`,{source:'scanner_reception_batch',scanSessionId:id,detail:`${serious.length} type(s) d'écart détecté(s)`,anomalies:serious,discrepancies},req.user.id]);}
    await c.query(`UPDATE scan_sessions SET status='completed',summary=$1,completed_at=now() WHERE id=$2 AND organization_id=$3`,[summary,id,org]);});await audit(req,'scanner.session.complete','scan_session',id,{kind:session.kind,...summary});res.json({ok:true,sessionId:id,kind:session.kind,summary});}));

export default r;
