import { Router } from 'express';
import crypto from 'node:crypto';
import { z } from 'zod';
import { q,tx } from '../db.js';
import { asyncRoute,HttpError } from '../utils/http.js';
import { requireUser,roles } from '../middleware/auth.js';
import { audit } from '../services/audit.js';
import { buildSupplierNeedsPdf,buildSupplierPreviewPdf,buildPurchaseOrderPdf } from '../services/supplier-report.js';
import { csvCell } from '../utils/csv.js';

const r=Router();
const uuid=z.string().uuid();
const supplierSchema=z.object({
  name:z.string().trim().min(2).max(160),email:z.string().trim().email().or(z.literal('')).optional(),phone:z.string().trim().max(50).optional(),accountNumber:z.string().trim().max(100).optional(),
  allowedOrderDays:z.array(z.number().int().min(1).max(7)).min(1).max(7),cutoffTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).or(z.literal('')).optional(),leadDays:z.coerce.number().int().min(0).max(30).default(1),minimumOrderEuros:z.coerce.number().min(0).max(100000).default(0),notes:z.string().trim().max(1000).optional(),active:z.boolean().optional()
});
const assignSchema=z.object({supplierId:z.string().uuid(),orderUnit:z.string().trim().min(1).max(40).default('unité'),packSize:z.coerce.number().positive().max(100000).default(1),defaultOrderQty:z.coerce.number().min(0).max(100000).default(1),unitPriceEuros:z.union([z.coerce.number().min(0).max(100000),z.literal(''),z.null()]).optional(),supplierReference:z.string().trim().max(100).optional()});
const needSchema=z.object({quantity:z.coerce.number().min(0).max(100000),note:z.string().trim().max(300).optional()});
const invoiceImportLineSchema=z.object({
  productName:z.string().trim().min(2).max(160),supplierReference:z.string().trim().max(100).optional().nullable(),
  invoiceQuantity:z.coerce.number().positive().max(100000).default(1),orderUnit:z.string().trim().min(1).max(40).default('unité'),
  packSize:z.coerce.number().positive().max(100000).default(1),unitPriceEuros:z.union([z.coerce.number().min(0).max(100000),z.literal(''),z.null()]).optional(),
  lineTotalEuros:z.union([z.coerce.number().min(0).max(10000000),z.literal(''),z.null()]).optional(),rawText:z.string().max(500).optional().nullable()
});
const invoiceImportSchema=z.object({
  supplierId:z.string().uuid(),mediaId:z.string().uuid().optional().nullable(),invoiceNo:z.string().trim().max(100).optional().nullable(),invoiceDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
  totalHtEuros:z.union([z.coerce.number().min(0).max(10000000),z.literal(''),z.null()]).optional(),totalTtcEuros:z.union([z.coerce.number().min(0).max(10000000),z.literal(''),z.null()]).optional(),
  ocrConfidence:z.coerce.number().int().min(0).max(100).optional().nullable(),lines:z.array(invoiceImportLineSchema).min(1).max(120)
});
const cents=v=>v===''||v==null?null:Math.round(Number(v)*100);

const dayLabels={1:'Lundi',2:'Mardi',3:'Mercredi',4:'Jeudi',5:'Vendredi',6:'Samedi',7:'Dimanche'};
const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0};
function parisParts(date=new Date()){
  const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));
  const dayMap={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7};return {day:dayMap[p.weekday],date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`};
}
function nextAllowedInfo(supplier){
  const allowed=(supplier.allowed_order_days||[]).map(Number);const now=parisParts();const todayAllowed=allowed.includes(now.day);const cutoff=String(supplier.cutoff_time||'').slice(0,5);const beforeCutoff=!cutoff||now.time<=cutoff;
  if(todayAllowed&&beforeCutoff)return {allowedToday:true,nextAllowedDate:now.date,nextAllowedLabel:'Aujourd’hui'};
  for(let i=todayAllowed&&!beforeCutoff?1:1;i<=7;i++){const d=new Date(Date.now()+i*86400000);const p=parisParts(d);if(allowed.includes(p.day))return {allowedToday:false,nextAllowedDate:p.date,nextAllowedLabel:`${dayLabels[p.day]} ${new Date(p.date+'T12:00:00').toLocaleDateString('fr-FR')}`};}
  return {allowedToday:false,nextAllowedDate:null,nextAllowedLabel:'Aucun jour configuré'};
}
function enrichSupplier(s){return {...s,...nextAllowedInfo(s),allowed_days_label:(s.allowed_order_days||[]).map(d=>dayLabels[Number(d)]).join(', ')};}
async function getSupplier(org,id){const s=(await q(`SELECT * FROM suppliers WHERE id=$1 AND organization_id=$2`,[id,org])).rows[0];if(!s)throw new HttpError(404,'Fournisseur introuvable.');return enrichSupplier(s);}
async function productRows(org){
  const {rows}=await q(`SELECT a.id stock_article_id,a.title article_title,a.payload article_payload,
    sp.id supplier_product_id,sp.supplier_id,sp.order_unit,sp.pack_size,sp.default_order_qty,sp.unit_price_cents,sp.supplier_reference,
    s.name supplier_name,s.allowed_order_days,s.cutoff_time,s.lead_days,s.minimum_order_cents,s.active supplier_active,
    n.quantity need_quantity,n.note need_note,n.ready_for_owner,n.updated_at need_updated_at,u.name need_updated_by
    FROM records a
    LEFT JOIN supplier_products sp ON sp.organization_id=a.organization_id AND sp.stock_article_id=a.id AND sp.active=true
    LEFT JOIN suppliers s ON s.id=sp.supplier_id
    LEFT JOIN supplier_order_needs n ON n.organization_id=a.organization_id AND n.stock_article_id=a.id
    LEFT JOIN users u ON u.id=n.updated_by
    WHERE a.organization_id=$1 AND a.type='stock_article' AND a.status<>'deleted'
    ORDER BY COALESCE(s.name,'ZZZ'),COALESCE(a.payload->>'product',a.title)`,[org]);
  return rows.map(x=>{const p=x.article_payload||{};const current=num(p.quantity),min=num(p.minStock),def=num(x.default_order_qty||1);const recommended=current<=min?(def>0?def:Math.max(1,min-current)):0;return {...x,product_name:p.product||x.article_title||'Produit',current_stock:current,min_stock:min,stock_unit:p.unit||'unité',need_quantity:num(x.need_quantity),recommended_quantity:recommended,supplier_info:x.supplier_id?enrichSupplier({allowed_order_days:x.allowed_order_days,cutoff_time:x.cutoff_time}):null};});
}

r.get('/',requireUser,asyncRoute(async(req,res)=>{const {rows}=await q(`SELECT * FROM suppliers WHERE organization_id=$1 ORDER BY active DESC,name`,[req.user.organization_id]);res.json(rows.map(enrichSupplier));}));
r.post('/',requireUser,roles('owner'),asyncRoute(async(req,res)=>{const d=supplierSchema.parse(req.body);const {rows}=await q(`INSERT INTO suppliers(organization_id,name,email,phone,account_number,allowed_order_days,cutoff_time,lead_days,minimum_order_cents,notes,active,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[req.user.organization_id,d.name,d.email||null,d.phone||null,d.accountNumber||null,d.allowedOrderDays,d.cutoffTime||null,d.leadDays,Math.round(d.minimumOrderEuros*100),d.notes||null,d.active??true,req.user.id]);await audit(req,'supplier.create','supplier',rows[0].id);res.status(201).json(enrichSupplier(rows[0]));}));
r.patch('/:id',requireUser,roles('owner'),asyncRoute(async(req,res)=>{const id=uuid.parse(req.params.id);const current=await getSupplier(req.user.organization_id,id);const d=supplierSchema.partial().parse(req.body);const allowed=d.allowedOrderDays??current.allowed_order_days;const {rows}=await q(`UPDATE suppliers SET name=COALESCE($1,name),email=$2,phone=$3,account_number=$4,allowed_order_days=$5,cutoff_time=$6,lead_days=COALESCE($7,lead_days),minimum_order_cents=COALESCE($8,minimum_order_cents),notes=$9,active=COALESCE($10,active) WHERE id=$11 AND organization_id=$12 RETURNING *`,[d.name??null,d.email===undefined?current.email:(d.email||null),d.phone===undefined?current.phone:(d.phone||null),d.accountNumber===undefined?current.account_number:(d.accountNumber||null),allowed,d.cutoffTime===undefined?current.cutoff_time:(d.cutoffTime||null),d.leadDays??null,d.minimumOrderEuros===undefined?current.minimum_order_cents:Math.round(d.minimumOrderEuros*100),d.notes===undefined?current.notes:(d.notes||null),d.active??null,id,req.user.organization_id]);await audit(req,'supplier.update','supplier',id);res.json(enrichSupplier(rows[0]));}));
r.delete('/:id',requireUser,roles('owner'),asyncRoute(async(req,res)=>{const id=uuid.parse(req.params.id);await getSupplier(req.user.organization_id,id);await q(`UPDATE suppliers SET active=false WHERE id=$1 AND organization_id=$2`,[id,req.user.organization_id]);await audit(req,'supplier.disable','supplier',id);res.json({ok:true});}));

r.get('/catalog/products',requireUser,asyncRoute(async(req,res)=>{res.json(await productRows(req.user.organization_id));}));
r.put('/catalog/products/:articleId',requireUser,roles('owner'),asyncRoute(async(req,res)=>{const articleId=uuid.parse(req.params.articleId);const d=assignSchema.parse(req.body);const article=(await q(`SELECT id FROM records WHERE id=$1 AND organization_id=$2 AND type='stock_article'`,[articleId,req.user.organization_id])).rows[0];if(!article)throw new HttpError(404,'Produit introuvable.');await getSupplier(req.user.organization_id,d.supplierId);const price=d.unitPriceEuros===''||d.unitPriceEuros==null?null:Math.round(Number(d.unitPriceEuros)*100);const {rows}=await q(`INSERT INTO supplier_products(organization_id,stock_article_id,supplier_id,order_unit,pack_size,default_order_qty,unit_price_cents,supplier_reference) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(organization_id,stock_article_id) DO UPDATE SET supplier_id=EXCLUDED.supplier_id,order_unit=EXCLUDED.order_unit,pack_size=EXCLUDED.pack_size,default_order_qty=EXCLUDED.default_order_qty,unit_price_cents=EXCLUDED.unit_price_cents,supplier_reference=EXCLUDED.supplier_reference,active=true RETURNING *`,[req.user.organization_id,articleId,d.supplierId,d.orderUnit,d.packSize,d.defaultOrderQty,price,d.supplierReference||null]);await audit(req,'supplier.product.assign','stock_article',articleId,{supplierId:d.supplierId});res.json(rows[0]);}));

r.put('/needs/:articleId',requireUser,asyncRoute(async(req,res)=>{const articleId=uuid.parse(req.params.articleId);const d=needSchema.parse(req.body);const article=(await q(`SELECT id FROM records WHERE id=$1 AND organization_id=$2 AND type='stock_article'`,[articleId,req.user.organization_id])).rows[0];if(!article)throw new HttpError(404,'Produit introuvable.');const {rows}=await q(`INSERT INTO supplier_order_needs(organization_id,stock_article_id,quantity,note,ready_for_owner,updated_by) VALUES($1,$2,$3,$4,false,$5) ON CONFLICT(organization_id,stock_article_id) DO UPDATE SET quantity=EXCLUDED.quantity,note=EXCLUDED.note,ready_for_owner=false,updated_by=EXCLUDED.updated_by,updated_at=now() RETURNING *`,[req.user.organization_id,articleId,d.quantity,d.note||null,req.user.id]);res.json(rows[0]);}));
r.post('/needs/mark-ready',requireUser,asyncRoute(async(req,res)=>{const {rowCount}=await q(`UPDATE supplier_order_needs SET ready_for_owner=true,updated_at=now(),updated_by=$2 WHERE organization_id=$1 AND quantity>0`,[req.user.organization_id,req.user.id]);await audit(req,'supplier.needs.ready','supplier_order_needs',null,{count:rowCount});res.json({ok:true,count:rowCount});}));

r.post('/invoice-imports',requireUser,roles('owner'),asyncRoute(async(req,res)=>{
  const d=invoiceImportSchema.parse(req.body);const org=req.user.organization_id;const supplier=await getSupplier(org,d.supplierId);
  if(!supplier.active)throw new HttpError(409,'Ce fournisseur est désactivé.');
  if(d.mediaId){const media=(await q(`SELECT id FROM media WHERE id=$1 AND organization_id=$2 AND kind='invoice'`,[d.mediaId,org])).rows[0];if(!media)throw new HttpError(400,'La facture enregistrée est introuvable.','invoice_media_missing');}
  if(d.invoiceNo){const duplicate=(await q(`SELECT id FROM supplier_invoice_imports WHERE organization_id=$1 AND supplier_id=$2 AND invoice_number=$3`,[org,d.supplierId,d.invoiceNo])).rows[0];if(duplicate)throw new HttpError(409,'Cette facture a déjà servi à créer une liste de commande.','invoice_already_imported');}
  const result=await tx(async c=>{
    const imp=(await c.query(`INSERT INTO supplier_invoice_imports(organization_id,supplier_id,source_media_id,invoice_number,invoice_date,total_ht_cents,total_ttc_cents,ocr_confidence,imported_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[org,d.supplierId,d.mediaId||null,d.invoiceNo||null,d.invoiceDate||null,cents(d.totalHtEuros),cents(d.totalTtcEuros),d.ocrConfidence??null,req.user.id])).rows[0];
    let created=0,matched=0;const articles=[];
    for(let i=0;i<d.lines.length;i++){
      const line=d.lines[i],name=line.productName.trim(),ref=line.supplierReference?.trim()||null,price=cents(line.unitPriceEuros),lineTotal=cents(line.lineTotalEuros);
      let sp=(await c.query(`SELECT sp.*,r.id stock_article_id FROM supplier_products sp JOIN records r ON r.id=sp.stock_article_id WHERE sp.organization_id=$1 AND sp.supplier_id=$2 AND sp.active=true AND (($3::text IS NOT NULL AND sp.supplier_reference=$3) OR lower(btrim(COALESCE(r.payload->>'product',r.title)))=lower(btrim($4))) ORDER BY CASE WHEN $3::text IS NOT NULL AND sp.supplier_reference=$3 THEN 0 ELSE 1 END LIMIT 1`,[org,d.supplierId,ref,name])).rows[0];
      let articleId,supplierProductId;
      if(sp){matched++;articleId=sp.stock_article_id;supplierProductId=sp.id;const updated=(await c.query(`UPDATE supplier_products SET order_unit=$1,pack_size=$2,default_order_qty=$3,unit_price_cents=COALESCE($4,unit_price_cents),supplier_reference=COALESCE($5,supplier_reference),active=true WHERE id=$6 RETURNING *`,[line.orderUnit,line.packSize,line.invoiceQuantity,price,ref,sp.id])).rows[0];supplierProductId=updated.id;}
      else{
        const article=(await c.query(`INSERT INTO records(organization_id,type,title,status,payload,created_by,updated_by) VALUES($1,'stock_article',$2,'active',$3,$4,$4) RETURNING *`,[org,name,{product:name,quantity:0,minStock:0,unit:line.orderUnit,source:'invoice_import'},req.user.id])).rows[0];articleId=article.id;
        const createdSp=(await c.query(`INSERT INTO supplier_products(organization_id,stock_article_id,supplier_id,order_unit,pack_size,default_order_qty,unit_price_cents,supplier_reference) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[org,articleId,d.supplierId,line.orderUnit,line.packSize,line.invoiceQuantity,price,ref])).rows[0];supplierProductId=createdSp.id;created++;
      }
      await c.query(`INSERT INTO supplier_invoice_import_lines(import_id,stock_article_id,supplier_product_id,product_name,supplier_reference,invoice_quantity,order_unit,unit_price_cents,line_total_cents,raw_text,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[imp.id,articleId,supplierProductId,name,ref,line.invoiceQuantity,line.orderUnit,price,lineTotal,line.rawText||null,i]);
      articles.push({stockArticleId:articleId,productName:name,created:!sp});
    }
    return {import:imp,created,matched,articles};
  });
  await audit(req,'supplier.invoice.import','supplier_invoice_import',result.import.id,{supplierId:d.supplierId,lines:d.lines.length,created:result.created,matched:result.matched});
  res.status(201).json({...result,supplierName:supplier.name,message:`${d.lines.length} produit(s) ajoutés au tableau partagé.`});
}));

r.get('/invoice-imports/history',requireUser,roles('owner','manager'),asyncRoute(async(req,res)=>{
  const {rows}=await q(`SELECT i.id,i.invoice_number,i.invoice_date,i.total_ht_cents,i.total_ttc_cents,i.ocr_confidence,i.created_at,i.source_media_id,s.name supplier_name,u.name imported_by_name,count(l.id)::int line_count FROM supplier_invoice_imports i JOIN suppliers s ON s.id=i.supplier_id LEFT JOIN users u ON u.id=i.imported_by LEFT JOIN supplier_invoice_import_lines l ON l.import_id=i.id WHERE i.organization_id=$1 GROUP BY i.id,s.name,u.name ORDER BY i.created_at DESC LIMIT 100`,[req.user.organization_id]);res.json(rows);
}));

r.get('/needs.pdf',requireUser,asyncRoute(async(req,res)=>{const [org,rows]=await Promise.all([q('SELECT * FROM organizations WHERE id=$1',[req.user.organization_id]),productRows(req.user.organization_id)]);const pdf=await buildSupplierNeedsPdf({organization:org.rows[0],user:req.user,rows});res.type('application/pdf').set('Content-Disposition','attachment; filename="hygiesafe-besoins-fournisseurs.pdf"').send(pdf);}));
r.get('/needs.csv',requireUser,asyncRoute(async(req,res)=>{const rows=await productRows(req.user.organization_id);const e=csvCell;const csv=['produit;fournisseur;stock;stock_minimum;quantite_conseillee;quantite_a_commander;unite;note',...rows.map(x=>[x.product_name,x.supplier_name||'',x.current_stock,x.min_stock,x.recommended_quantity,x.need_quantity,x.order_unit||x.stock_unit,x.need_note||''].map(e).join(';'))].join('\n');res.type('text/csv; charset=utf-8').set('Content-Disposition','attachment; filename="hygiesafe-besoins-fournisseurs.csv"').send('\ufeff'+csv);}));

r.get('/:id/preview.pdf',requireUser,asyncRoute(async(req,res)=>{const id=uuid.parse(req.params.id);const supplier=await getSupplier(req.user.organization_id,id);const rows=(await productRows(req.user.organization_id)).filter(x=>x.supplier_id===supplier.id&&x.need_quantity>0);if(!rows.length)throw new HttpError(400,'Aucune quantité à commander pour ce fournisseur.');const org=(await q('SELECT * FROM organizations WHERE id=$1',[req.user.organization_id])).rows[0];const pdf=await buildSupplierPreviewPdf({organization:org,user:req.user,supplier,rows});res.type('application/pdf').set('Content-Disposition',`attachment; filename="preparation-${supplier.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.pdf"`).send(pdf);}));

r.get('/orders/history',requireUser,asyncRoute(async(req,res)=>{const {rows}=await q(`SELECT po.*,s.name supplier_name,u.name approved_by_name,(SELECT count(*)::int FROM purchase_order_lines l WHERE l.order_id=po.id) line_count FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id LEFT JOIN users u ON u.id=po.approved_by WHERE po.organization_id=$1 ORDER BY po.submitted_at DESC LIMIT 100`,[req.user.organization_id]);res.json(rows);}));
r.post('/:id/orders/submit',requireUser,roles('owner'),asyncRoute(async(req,res)=>{const id=uuid.parse(req.params.id);const supplier=await getSupplier(req.user.organization_id,id);if(!supplier.active)throw new HttpError(409,'Ce fournisseur est désactivé.');const availability=nextAllowedInfo(supplier);if(!availability.allowedToday)throw new HttpError(409,`Commande impossible aujourd’hui. Prochain jour autorisé : ${availability.nextAllowedLabel}.`,'supplier_day');const rows=(await productRows(req.user.organization_id)).filter(x=>x.supplier_id===supplier.id&&x.need_quantity>0);if(!rows.length)throw new HttpError(400,'Aucune quantité à commander pour ce fournisseur.');const allPriced=rows.every(x=>x.unit_price_cents!=null);const total=rows.reduce((s,x)=>s+Math.round(Number(x.need_quantity)*Number(x.unit_price_cents||0)),0);if(supplier.minimum_order_cents>0&&allPriced&&total<supplier.minimum_order_cents)throw new HttpError(409,`Minimum fournisseur non atteint : ${(supplier.minimum_order_cents/100).toFixed(2).replace('.',',')} €.`,'minimum_order');const local=parisParts();const orderNumber=`HP-${local.date.replaceAll('-','')}-${crypto.randomUUID().slice(0,4).toUpperCase()}`;const expectedDate=new Date(Date.now()+Number(supplier.lead_days||0)*86400000).toISOString().slice(0,10);const order=await tx(async c=>{const o=(await c.query(`INSERT INTO purchase_orders(organization_id,supplier_id,order_number,status,expected_delivery_date,total_estimated_cents,prepared_by,approved_by) VALUES($1,$2,$3,'submitted',$4,$5,$6,$6) RETURNING *`,[req.user.organization_id,supplier.id,orderNumber,expectedDate,total,req.user.id])).rows[0];for(const x of rows)await c.query(`INSERT INTO purchase_order_lines(order_id,stock_article_id,product_name,supplier_reference,order_unit,quantity,pack_size,unit_price_cents,current_stock,min_stock) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[o.id,x.stock_article_id,x.product_name,x.supplier_reference||null,x.order_unit||x.stock_unit||'unité',x.need_quantity,x.pack_size||1,x.unit_price_cents,x.current_stock,x.min_stock]);await c.query(`DELETE FROM supplier_order_needs n USING supplier_products sp WHERE n.organization_id=$1 AND sp.organization_id=$1 AND n.stock_article_id=sp.stock_article_id AND sp.supplier_id=$2`,[req.user.organization_id,supplier.id]);return o;});await audit(req,'purchase_order.submit','purchase_order',order.id,{supplierId:supplier.id,lines:rows.length,total});res.status(201).json({...order,supplier_name:supplier.name});}));
r.get('/orders/:orderId.pdf',requireUser,roles('owner','manager'),asyncRoute(async(req,res)=>{const orderId=uuid.parse(req.params.orderId);const order=(await q(`SELECT po.*,s.name supplier_name FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id WHERE po.id=$1 AND po.organization_id=$2`,[orderId,req.user.organization_id])).rows[0];if(!order)throw new HttpError(404,'Commande introuvable.');const [supplier,org,lines]=await Promise.all([getSupplier(req.user.organization_id,order.supplier_id),q('SELECT * FROM organizations WHERE id=$1',[req.user.organization_id]),q('SELECT * FROM purchase_order_lines WHERE order_id=$1 ORDER BY product_name',[order.id])]);const pdf=await buildPurchaseOrderPdf({organization:org.rows[0],user:req.user,order,supplier,lines:lines.rows});res.type('application/pdf').set('Content-Disposition',`attachment; filename="${order.order_number}.pdf"`).send(pdf);}));
r.get('/orders/:orderId.csv',requireUser,roles('owner','manager'),asyncRoute(async(req,res)=>{const orderId=uuid.parse(req.params.orderId);const order=(await q(`SELECT po.*,s.name supplier_name FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id WHERE po.id=$1 AND po.organization_id=$2`,[orderId,req.user.organization_id])).rows[0];if(!order)throw new HttpError(404,'Commande introuvable.');const lines=(await q('SELECT * FROM purchase_order_lines WHERE order_id=$1 ORDER BY product_name',[order.id])).rows;const e=csvCell;const csv=['commande;fournisseur;produit;reference;quantite;unite;prix_unitaire_cents',...lines.map(x=>[order.order_number,order.supplier_name,x.product_name,x.supplier_reference||'',x.quantity,x.order_unit,x.unit_price_cents??''].map(e).join(';'))].join('\n');res.type('text/csv; charset=utf-8').set('Content-Disposition',`attachment; filename="${order.order_number}.csv"`).send('\ufeff'+csv);}));

export default r;
