import { q } from '../db.js';
import { config } from '../config.js';
import { APP_VERSION } from '../version.js';

const FOUND_TTL_MS=30*24*60*60*1000;
const NOT_FOUND_TTL_MS=24*60*60*1000;
const ERROR_TTL_MS=15*60*1000;

export function normalizeBarcode(value){const digits=String(value||'').replace(/\D/g,'');return digits.length>=8&&digits.length<=14?digits:null;}
function safeHttps(value){try{const u=new URL(String(value||''));return u.protocol==='https:'?u.toString():null}catch{return null}}
function first(value){return Array.isArray(value)?value.find(Boolean):value}
function cleanText(value,max=1200){const s=String(value||'').replace(/\s+/g,' ').trim();return s?s.slice(0,max):null}
function listText(value,max=600){if(Array.isArray(value))return cleanText(value.map(x=>typeof x==='string'?x:(x?.lc_name||x?.id||'')).filter(Boolean).join(', '),max);return cleanText(value,max)}

export function mapOpenFoodFactsProduct(code,body){
  const p=body?.product||null;if(!p)return null;const name=cleanText(p.product_name||p.product_name_fr||p.abbreviated_product_name||p.generic_name||p.generic_name_fr,220);if(!name)return null;
  const image=safeHttps(p.image_front_url||p.image_url||p.selected_images?.front?.display?.fr||p.selected_images?.front?.display?.en),productCode=normalizeBarcode(p.code||code)||normalizeBarcode(code);
  return {code:productCode||String(code||''),name,brand:cleanText(p.brands,180),category:cleanText(p.categories,300),quantityLabel:cleanText(p.quantity,120),productQuantity:p.product_quantity==null?null:Number(p.product_quantity),productQuantityUnit:cleanText(p.product_quantity_unit,30),imageUrl:image,ingredients:cleanText(p.ingredients_text||p.ingredients_text_fr,1800),allergens:listText(p.allergens||p.allergens_tags,700),traces:listText(p.traces||p.traces_tags,500),labels:listText(p.labels||p.labels_tags,500),countries:listText(p.countries||p.countries_tags,500),origins:listText(p.origins||p.origins_tags,500),manufacturingPlaces:cleanText(p.manufacturing_places,500),embCodes:cleanText(p.emb_codes,300),nutritionGrade:cleanText(p.nutriscore_grade||p.nutrition_grades,20),ecoscoreGrade:cleanText(p.ecoscore_grade,20),completeness:Number.isFinite(Number(p.completeness))?Number(p.completeness):null,source:'open_food_facts',sourceLabel:'Open Food Facts',sourceUrl:`https://world.openfoodfacts.org/product/${encodeURIComponent(productCode||code)}`,sourceLicense:'ODbL',sourceAttribution:'Données produit : Open Food Facts — ODbL (consultées à la demande, non fusionnées dans le catalogue propriétaire)',verifiedByGs1Url:'https://www.gs1.org/services/verified-by-gs1'};
}
export function mapUpcItemDbItem(code,item){if(!item)return null;const name=cleanText(item.title||item.description,220);if(!name)return null;const productCode=normalizeBarcode(item.ean||item.upc||code)||normalizeBarcode(code);return {code:productCode||String(code||''),name,brand:cleanText(item.brand,180),category:cleanText(item.category,300),quantityLabel:cleanText(item.size,120),productQuantity:null,productQuantityUnit:null,imageUrl:safeHttps(first(item.images)),ingredients:null,allergens:null,traces:null,labels:null,countries:null,origins:null,manufacturingPlaces:null,embCodes:null,nutritionGrade:null,ecoscoreGrade:null,completeness:null,source:'upcitemdb',sourceLabel:'UPCitemdb',sourceUrl:`https://www.upcitemdb.com/upc/${encodeURIComponent(productCode||code)}`,sourceLicense:null,sourceAttribution:'Informations produit : UPCitemdb',verifiedByGs1Url:'https://www.gs1.org/services/verified-by-gs1'};}
async function fetchJson(url,{headers={},timeoutMs=config.productLookup?.timeoutMs||4500}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Math.max(1000,timeoutMs));try{const r=await fetch(url,{headers:{Accept:'application/json',...headers},signal:controller.signal,redirect:'follow'});if(r.status===404||r.status===429)return {status:r.status,body:null,headers:r.headers};if(!r.ok)return {status:r.status,body:null,headers:r.headers};const text=await r.text();let body=null;try{body=JSON.parse(text)}catch{return {status:502,body:null,headers:r.headers}}return {status:r.status,body,headers:r.headers};}finally{clearTimeout(timer)}}
async function fetchOpenFoodFacts(code){if(config.productLookup?.openFoodFacts===false)return {found:false,provider:'open_food_facts',skipped:true};const fields=['code','product_name','abbreviated_product_name','generic_name','brands','categories','quantity','product_quantity','product_quantity_unit','image_front_url','image_url','selected_images','ingredients_text','allergens','allergens_tags','traces','traces_tags','labels','labels_tags','countries','countries_tags','origins','origins_tags','manufacturing_places','emb_codes','nutriscore_grade','nutrition_grades','ecoscore_grade','completeness'].join(','),url=`https://world.openfoodfacts.org/api/v3/product/${encodeURIComponent(code)}?product_type=all&cc=fr&lc=fr&tags_lc=fr&fields=${encodeURIComponent(fields)}`;try{const r=await fetchJson(url,{headers:{'User-Agent':`HygieSafe/${APP_VERSION} (${config.publicSiteUrl||config.appUrl||'https://www.hygiesafe.com'})`}});if(r.status===404)return {found:false,provider:'open_food_facts'};if(r.status!==200)return {found:false,provider:'open_food_facts',error:`http_${r.status}`};const product=mapOpenFoodFactsProduct(code,r.body);return product?{found:true,provider:'open_food_facts',product}:{found:false,provider:'open_food_facts'};}catch(e){return {found:false,provider:'open_food_facts',error:e?.name==='AbortError'?'timeout':'network'}}}
async function fetchUpcItemDb(code){if(config.productLookup?.upcItemDb===false)return {found:false,provider:'upcitemdb',skipped:true};const paid=!!config.productLookup?.upcItemDbUserKey,base=paid?'https://api.upcitemdb.com/prod/v1/lookup':'https://api.upcitemdb.com/prod/trial/lookup',headers=paid?{user_key:config.productLookup.upcItemDbUserKey,key_type:config.productLookup.upcItemDbKeyType||'3scale'}:{};try{const r=await fetchJson(`${base}?upc=${encodeURIComponent(code)}`,{headers});if(r.status===404)return {found:false,provider:'upcitemdb'};if(r.status===429)return {found:false,provider:'upcitemdb',error:'rate_limited'};if(r.status!==200)return {found:false,provider:'upcitemdb',error:`http_${r.status}`};const product=mapUpcItemDbItem(code,r.body?.items?.[0]);return product?{found:true,provider:'upcitemdb',product}:{found:false,provider:'upcitemdb'};}catch(e){return {found:false,provider:'upcitemdb',error:e?.name==='AbortError'?'timeout':'network'}}}
async function localArticle(organizationId,code){return (await q(`SELECT id,title,payload,updated_at FROM records WHERE organization_id=$1 AND type='stock_article' AND status<>'deleted' AND regexp_replace(COALESCE(payload->>'barcode',''),'[^0-9]','','g')=$2 ORDER BY updated_at DESC LIMIT 1`,[organizationId,code])).rows[0]||null;}
async function memoryProduct(organizationId,code){return (await q(`SELECT * FROM organization_product_memory WHERE organization_id=$1 AND barcode=$2 LIMIT 1`,[organizationId,code])).rows[0]||null;}
function memoryToProduct(row){if(!row)return null;return {code:row.barcode,name:row.product_name,brand:row.brand||null,category:row.category||null,quantityLabel:row.quantity_label||null,imageUrl:row.image_url||null,source:'hygiesafe_memory',sourceLabel:'Catalogue HygieSafe',sourceUrl:null,sourceLicense:null,sourceAttribution:'Nom de produit confirmé par un utilisateur de cet établissement',memoryId:row.id};}
function articleToProduct(row,code){const p=row.payload||{};return {code,name:p.product||row.title||'Article',brand:p.brand||null,category:p.category||null,quantityLabel:p.packageSize||p.quantityLabel||null,imageUrl:safeHttps(p.imageUrl),ingredients:p.ingredients||null,allergens:p.allergens||null,traces:p.traces||null,labels:p.labels||null,countries:p.countries||null,origins:p.origins||null,manufacturingPlaces:p.manufacturingPlaces||null,embCodes:p.embCodes||null,nutritionGrade:p.nutritionGrade||null,ecoscoreGrade:p.ecoscoreGrade||null,source:'hygiesafe_catalog',sourceLabel:'Catalogue HygieSafe',sourceUrl:null,sourceLicense:null,sourceAttribution:'Article déjà configuré dans cet établissement',articleId:row.id};}
async function readUpcCache(code){const row=(await q(`SELECT * FROM external_product_cache WHERE barcode=$1 AND source='upcitemdb' LIMIT 1`,[code])).rows[0]||null;if(!row)return null;await q(`UPDATE external_product_cache SET hit_count=hit_count+1,last_accessed_at=now() WHERE barcode=$1 AND source='upcitemdb'`,[code]).catch(()=>{});return new Date(row.expires_at).getTime()>Date.now()?row:null;}
async function writeUpcCache(code,{status,product=null,attempts=[]}){const ttl=status==='found'?FOUND_TTL_MS:status==='not_found'?NOT_FOUND_TTL_MS:ERROR_TTL_MS,expires=new Date(Date.now()+ttl).toISOString();await q(`INSERT INTO external_product_cache(barcode,status,source,payload,attempts,fetched_at,expires_at,last_accessed_at,hit_count) VALUES($1,$2,'upcitemdb',$3,$4,now(),$5,now(),0) ON CONFLICT(barcode) DO UPDATE SET status=EXCLUDED.status,source='upcitemdb',payload=EXCLUDED.payload,attempts=EXCLUDED.attempts,fetched_at=now(),expires_at=EXCLUDED.expires_at,last_accessed_at=now()`,[code,status,product||{},attempts,expires]);}
export async function lookupProduct({organizationId,code,forceRefresh=false}){const barcode=normalizeBarcode(code);if(!barcode)return {found:false,code:null,error:'invalid_barcode',attempts:[]};const article=await localArticle(organizationId,barcode);if(article)return {found:true,code:barcode,source:'hygiesafe_catalog',product:articleToProduct(article,barcode),cached:true,attempts:[]};const memory=await memoryProduct(organizationId,barcode);if(memory){await q(`UPDATE organization_product_memory SET last_seen_at=now(),seen_count=seen_count+1 WHERE id=$1`,[memory.id]).catch(()=>{});return {found:true,code:barcode,source:'hygiesafe_memory',product:memoryToProduct(memory),cached:true,attempts:[]};}
  const attempts=[];const off=await fetchOpenFoodFacts(barcode);attempts.push({provider:'open_food_facts',found:!!off.found,error:off.error||null,skipped:!!off.skipped});if(off.found)return {found:true,code:barcode,source:'open_food_facts',product:off.product,cached:false,attempts};
  if(!forceRefresh){const cache=await readUpcCache(barcode);if(cache){if(cache.status==='found')return {found:true,code:barcode,source:'upcitemdb',product:cache.payload,cached:true,attempts:[...attempts,...(cache.attempts||[])]};if(cache.status==='not_found')return {found:false,code:barcode,cached:true,attempts:[...attempts,...(cache.attempts||[])],gs1VerificationUrl:'https://www.gs1.org/services/verified-by-gs1'};}}
  const upc=await fetchUpcItemDb(barcode);attempts.push({provider:'upcitemdb',found:!!upc.found,error:upc.error||null,skipped:!!upc.skipped});if(upc.found){await writeUpcCache(barcode,{status:'found',product:upc.product,attempts:[attempts.at(-1)]}).catch(()=>{});return {found:true,code:barcode,source:'upcitemdb',product:upc.product,cached:false,attempts};}await writeUpcCache(barcode,{status:upc.error?'error':'not_found',attempts:[attempts.at(-1)]}).catch(()=>{});return {found:false,code:barcode,cached:false,temporarilyUnavailable:!!upc.error&&!!off.error,attempts,gs1VerificationUrl:'https://www.gs1.org/services/verified-by-gs1'};
}
export async function rememberProduct({organizationId,userId,code,product,overrideName=null,allowRename=true}){const barcode=normalizeBarcode(code);if(!barcode||!product?.name)return null;const name=cleanText(overrideName||product.name,220);if(!name)return null;const existing=await memoryProduct(organizationId,barcode);if(existing&&!allowRename){return (await q(`UPDATE organization_product_memory SET last_seen_at=now(),seen_count=seen_count+1,verified_by=$1 WHERE id=$2 RETURNING *`,[userId,existing.id])).rows[0]||existing;}const external=['open_food_facts','upcitemdb'].includes(product.source);const brand=external?null:cleanText(product.brand,180),category=external?null:cleanText(product.category,300),quantityLabel=external?null:cleanText(product.quantityLabel,120),imageUrl=external?null:safeHttps(product.imageUrl),source=external?'manual_confirmation':(product.source||'manual'),sourceData={confirmationOrigin:external?product.source:null};return (await q(`INSERT INTO organization_product_memory(organization_id,barcode,product_name,brand,category,quantity_label,image_url,source,source_url,source_license,source_data,verified_by,first_seen_at,last_seen_at,seen_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8,NULL,NULL,$9,$10,now(),now(),1) ON CONFLICT(organization_id,barcode) DO UPDATE SET product_name=EXCLUDED.product_name,brand=EXCLUDED.brand,category=EXCLUDED.category,quantity_label=EXCLUDED.quantity_label,image_url=EXCLUDED.image_url,source=EXCLUDED.source,source_url=NULL,source_license=NULL,source_data=EXCLUDED.source_data,verified_by=EXCLUDED.verified_by,last_seen_at=now(),seen_count=organization_product_memory.seen_count+1,updated_at=now() RETURNING *`,[organizationId,barcode,name,brand,category,quantityLabel,imageUrl,source,sourceData,userId])).rows[0]||null;}
