import fs from 'node:fs';import path from 'node:path';import { execFileSync } from 'node:child_process';
const root=path.resolve(new URL('..',import.meta.url).pathname);let fail=0;
function ok(msg){console.log('✓',msg)}function bad(msg){fail++;console.error('✗',msg)}
for(const file of fs.readdirSync(path.join(root,'src'),{recursive:true}).filter(x=>String(x).endsWith('.js'))){const p=path.join(root,'src',String(file));try{execFileSync(process.execPath,['--check',p],{stdio:'ignore'});ok('JS '+file)}catch{bad('JS '+file)}}
for(const file of fs.readdirSync(path.join(root,'public','js')).filter(x=>x.endsWith('.js'))){const p=path.join(root,'public','js',file);try{execFileSync(process.execPath,['--check',p],{stdio:'ignore'});ok('Public JS '+file)}catch{bad('Public JS '+file)}}
for(const f of ['index.html','login.html','register.html','app.html','admin.html','invite.html','reset.html','legal.html','privacy.html','terms.html','cgv.html','verify-email.html','faq.html']){fs.existsSync(path.join(root,'public',f))?ok(f):bad('missing '+f)}

const faq=fs.readFileSync(path.join(root,'public','faq.html'),'utf8');const faqCount=(faq.match(/<details data-faq>/g)||[]).length;faqCount>=10?ok(`FAQ ${faqCount} réponses`):bad(`FAQ insuffisante (${faqCount})`);const home=fs.readFileSync(path.join(root,'public','index.html'),'utf8');!home.includes('<h2>Questions fréquentes</h2>')?ok('FAQ retirée de l’accueil'):bad('ancienne FAQ encore sur accueil');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'public','manifest.webmanifest'),'utf8'));manifest.name==='HygieSafe'?ok('manifest HygieSafe'):bad('manifest name');
try{execFileSync(process.execPath,[path.join(root,'scripts','test-scanner.js')],{stdio:'inherit'});ok('scanner terrain')}catch{bad('scanner terrain')}
for(const f of ['db/migrations/004_supplier_orders.sql','db/migrations/006_security_billing_email.sql','db/migrations/007_invoice_order_lists.sql','db/migrations/008_backup_resend.sql','db/migrations/009_app_version_633.sql','db/migrations/010_app_version_634.sql','db/migrations/011_app_version_635.sql','db/migrations/012_app_version_640.sql','db/migrations/013_app_version_641.sql','db/migrations/014_app_version_642.sql','db/migrations/015_app_version_643.sql','db/migrations/016_app_version_644_legal_domain.sql','db/migrations/017_app_version_645_legal_minimal.sql','db/migrations/018_app_version_646_faq.sql','db/migrations/019_employee_temperature_schedules.sql','db/migrations/020_app_version_648_admin_observability.sql','db/migrations/021_role_tutorials_ux.sql','db/migrations/022_price_999_admin_ux.sql','db/migrations/023_app_version_652_professional_emails.sql','db/migrations/024_app_version_653_admin_bootstrap.sql','db/migrations/025_app_version_654_scanner.sql','db/migrations/026_scanner_pro_sessions.sql','db/migrations/027_product_lookup_catalog.sql','db/migrations/028_production_hardening_657.sql','src/routes/scanner.js','src/services/product-lookup.js','src/utils/gs1.js','src/services/backup.js','src/utils/backup-path.js','src/routes/suppliers.js','src/services/supplier-report.js','public/assets/logo-hygiesafe.png']){fs.existsSync(path.join(root,f))?ok(f):bad('missing '+f)}
const app=fs.readFileSync(path.join(root,'public','app.html'),'utf8');app.includes('page-suppliers')?ok('page fournisseurs'):bad('page fournisseurs');app.includes('/assets/logo-hygiesafe.png')?ok('logo HygieSafe'):bad('logo HygieSafe');
const visiblePublic=fs.readdirSync(path.join(root,'public'),{recursive:true}).filter(x=>/\.(?:html|js|css|json|webmanifest|svg)$/i.test(String(x))).map(x=>{try{return fs.readFileSync(path.join(root,'public',String(x)),'utf8')}catch{return ''}}).join('\n');!visiblePublic.includes('HygiePro')?ok('ancienne marque absente du public'):bad('ancienne marque HygiePro encore visible');
if(fail)process.exit(1);console.log('HygieSafe v6.5.7 : contrôles statiques OK');
